// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAfbDlwOzS8zjw-rKTZE4bw-Xh-WFeKi4',
    appId: '1:777793287836:web:5021d59babc295f9535f59',
    messagingSenderId: '777793287836',
    projectId: 'delshop-fa6f7',
    authDomain: 'delshop-fa6f7.firebaseapp.com',
    storageBucket: 'delshop-fa6f7.firebasestorage.app',
    measurementId: 'G-5K33ZZQ2CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9Edcu8wiqRXircQC3ev5rnP_wfPssLk',
    appId: '1:777793287836:android:9f53fbb5f95ca616535f59',
    messagingSenderId: '777793287836',
    projectId: 'delshop-fa6f7',
    storageBucket: 'delshop-fa6f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkuBNwksbQgNYiUOJTOSF-bIRTVYsbAcQ',
    appId: '1:777793287836:ios:3a30e51b51e06bfd535f59',
    messagingSenderId: '777793287836',
    projectId: 'delshop-fa6f7',
    storageBucket: 'delshop-fa6f7.firebasestorage.app',
    iosBundleId: 'com.example.delshopFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkuBNwksbQgNYiUOJTOSF-bIRTVYsbAcQ',
    appId: '1:777793287836:ios:3a30e51b51e06bfd535f59',
    messagingSenderId: '777793287836',
    projectId: 'delshop-fa6f7',
    storageBucket: 'delshop-fa6f7.firebasestorage.app',
    iosBundleId: 'com.example.delshopFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAfbDlwOzS8zjw-rKTZE4bw-Xh-WFeKi4',
    appId: '1:777793287836:web:146705302085570c535f59',
    messagingSenderId: '777793287836',
    projectId: 'delshop-fa6f7',
    authDomain: 'delshop-fa6f7.firebaseapp.com',
    storageBucket: 'delshop-fa6f7.firebasestorage.app',
    measurementId: 'G-E31846QKQQ',
  );
}
